#+TITLE: Namaste, my name is Suryaansh 🌞
#+AUTHOR: Suryaansh Chawla
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://gongzhitaao.org/orgcss/org.css" />

#+EXPORT_FILE_NAME: index.html

https://cloud-fhk8pfxg9-hack-club-bot.vercel.app/0webp.net-resizeimage.png

* Introduction:
I am a 15 year old computer lover. Some of my favourite tools include: \\
+ Emacs (This site is written with org-mode <3) \\
+ GNU/Linux - Ditch proprietary stuff right now! \\

I enjoy teaching. I help students at a non-profit [[https://schoolhouse.world/tutor/838][Schoolhouse.world]]. \\

I created my school's first ever CS club. Big thanks to the non-profit [[https://apacdirectory.hackclub.com/club/brightqcbyteclub][Hack Club]].\\

* Check me out:
  
My blog at: [[https://medium.com/@suryaanshchawla][Medium]] \\

Check out my projects at: [[https://github.com/suryaanshah][Github]] \\

Here's my public learning diary:  [[https://scrapbook.hackclub.com/SuryaanshChawla-U02QN9S567M][Scrapbook]] \\

* How to reach out to me:

Message me on [[https://getsession.org/][Session]] : 056fc5c23a95e2bb21762a0b4453f2e92ac4494307d39c9cee3fcff16c47d9dc5d \\

Email me: [[mailto:suryaanshchawla@gmail.com][suryaanshchawla@gmail.com]] OR if you want to stay anonymous, I accept guerilla mail too. \\
OR try emailing my tutanota email: [[mailto:ghsur@tutanota.com][ghsur@tutanota.com]] 

Message me on: [[https://app.slack.com/client/T0266FRGM/C01504DCLVD/user_profile/U02QN9S567M][Slack]] \\

* Donate to me for fun:
You can donate to me using monero: 85L2Ybj7E3iSLHLpbQVeeja6cUigjwSaiDm3BDjahCXdcr6LUE36tYh3CJKChpnY1W1Ky5w2K3fddToKRgwP6VboJ9em1Mj
I am not a non-profit. You are responsible for you own donations. This is just added for fun.
